version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=a123456789A
    command: ['redis-server','--requirepass','a123456789A']
  
    